root_dir: '/home/user/zeng/dataset/binary_class'
gpu_ids: 1,2,4
base_image_size: 600
crop_size: (300, 400)
batch_size: 4
val_batch_size: 4

# the same in both developer_config.yaml and server.yaml
num_classes: 2