root_dir: '/home/zeng/dataset/pepper_binary'
gpu_ids: '3'
#base_image_size: (720,1280)
base_image_size: (600,800)
crop_image_size: (300,400)
train_batch_size: 16
val_batch_size: 16

num_workers: 8
resume: False
resume_path: "assets/trained_models/model_ep_44_bt_2000.pkl"
# the same in both developer_config.yaml and server.yaml
num_classes: 4